# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1b40509397af61dee5e4ad38b09f32bf67898d135a397d7838c90813d6a60376ee15173dc7a27ec568350d673f6b773bff6fcdcdf76a22152d7ea8dd2f4fc44b

test:
  secret_key_base: 1b4fe95f815be191a05468c4ac155a8c372b6de808ad9444a071efca57f056de5ab5ebd361d96881283116c6792e8fc368105720a7b8ba52079b277541a21009

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
